### ISSUE TITLE
Provide Sample GithubAction Workflow

### ISSUE THREAD

**Issue by Habikki** [NeoAgi/NeoAgi.AWS.CodeArtifact.Pruner#10]
An example workflow to execute the docker image would be helpful to provide, something like:

```
# This is a basic workflow to help you get started with Actions

name: Prune Code Artifact Repositories

# Controls when the workflow will run
on:
  # Run by default monthly
  schedule:
    - cron: "5 2 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      KEY_ID: ${{ secrets.SOME_KEY_ID }}
      KEY_SECRET: ${{ secrets.SOME_SECRET_KEY }}

    steps:
      - name: Notify
        uses: neoagi/actions-slack-notify@latest
        with:
          action-message: "Pruning NeoAgi AWS CodeArtifact Repositories"
          
      - name: Execute Pruner Docker
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${KEY_ID} -e AWS_SECRET_ACCESS_KEY=${KEY_SECRET} -t public.ecr.aws/neoagi/neoagi.aws.codeartifact.pruner:latest --domain neoagi --repository neoagi,nuget-store
        shell: bash

      - name: Notify
        uses: neoagi/actions-slack-notify@latest
        if: always()
```
